//! Deterministic hook installer (`scryrs init --agent <NAME>`).
//!
//! Two integration shapes:
//!
//! - **claude-code**: no hook file. The installer create-or-merges
//!   `.claude/settings.json` with a native `PreToolUse` command hook invoking
//!   `scryrs hook claude-code`. No JavaScript / node runtime is involved.
//! - **pi**: an in-process extension. The slimmed `hooks/pi/index.ts` is
//!   embedded at compile time via `include_str!()` and written to
//!   `.pi/extensions/scryrs/index.ts`.
//!
//! Two install modes:
//!
//! - **live** (default): creates or merges the `scryrs.json` `remote` section as the
//!   committed source of truth (`ingest_url`, `workspace_id`, `docker_network`), scaffolds
//!   an overrides-only `.scryrs/.env` and `.scryrs/compose.yml`, and does not create a local
//!   database. `repository_id` is derived from the Git remote origin and `agent_id` is
//!   autogenerated per container; neither is written to committed config.
//! - **local**: scaffolds `.scryrs/scryrs.db` for local SQLite trace storage.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use crate::live_bootstrap::{SCRYRS_COMPOSE_TEMPLATE, SCRYRS_DOCKER_NETWORK_ENV};
use crate::remote_config::{self, RemoteConfig, RemoteOverrides};

/// The native Claude Code `PreToolUse` hook command.
const CLAUDE_HOOK_COMMAND: &str = "scryrs hook claude-code";

/// Deterministic post-install instructions for Claude Code (no `.mjs`).
const CLAUDE_NEXT_STEPS: &str = concat!(
    "scryrs Claude Code hook configured in .claude/settings.json\n",
    "The PreToolUse hook command is: scryrs hook claude-code\n",
    "\n",
    "Next steps:\n",
    "  1. Ensure scryrs is on your PATH.\n",
    "  2. Restart your Claude Code session for the hook to take effect.\n",
);

// ---------------------------------------------------------------------------
// File-based harness registry (Pi). Claude Code is handled separately.
// ---------------------------------------------------------------------------

/// One entry in the file-based harness registry.
struct HarnessEntry {
    /// Canonical agent name (lowercase, e.g. "pi").
    agent_name: &'static str,
    /// Full hook source embedded at compile time.
    source_asset: &'static str,
    /// Target directory relative to the base dir (created if missing).
    target_dir: &'static str,
    /// Target filename within `target_dir`.
    target_filename: &'static str,
    /// Deterministic post-install instructions printed to stdout on success.
    next_steps: &'static str,
}

/// File-based harness registry. Claude Code is NOT here — it merges JSON.
const FILE_HARNESS_REGISTRY: &[HarnessEntry] = &[HarnessEntry {
    agent_name: "pi",
    // Path relative to this file: 3 levels up to repo root, then hooks/.
    source_asset: include_str!("../../../hooks/pi/index.ts"),
    target_dir: ".pi/extensions/scryrs",
    target_filename: "index.ts",
    next_steps: concat!(
        "scryrs Pi trace hook installed to .pi/extensions/scryrs/index.ts\n",
        "\n",
        "Next steps:\n",
        "  1. Ensure scryrs is on your PATH.\n",
        "  2. Reload Pi (e.g., /reload) to activate the hook.\n",
        "  3. The thin shim forwards raw Pi tool_result/session_start events to\n",
        "     `scryrs hook pi`; all tool→event translation lives in scryrs.\n",
    ),
}];

/// All supported harness names, for the unsupported-harness error message.
/// Ordered deterministically (alphabetical).
const SUPPORTED_HARNESSES: &[&str] = &["claude-code", "pi"];

/// `.gitignore` written into `.scryrs/` so runtime trace data is never
/// committed. Ignores everything in the directory except the ignore file
/// itself (covers `scryrs.db`, `hotspots.json`, and `hooks/`).
const SCRYRS_GITIGNORE: &str = concat!(
    "# scryrs runtime data — do not commit\n",
    "*\n",
    "!.gitignore\n",
);

/// Deterministic confirmation printed after the `.scryrs/` store is scaffolded.
const SCRYRS_SCAFFOLD_NOTE: &str =
    "Initialized .scryrs/ trace store (.scryrs/scryrs.db, .scryrs/.gitignore)\n\n";

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Install mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InitMode {
    /// Local SQLite trace store (default).
    Local,
    /// Remote ingest via scryrs server (writes project scryrs.json).
    Live,
}

/// Execute the `scryrs init --agent <NAME>` subcommand.
///
/// Returns the process exit code:
/// - 0: successful installation
/// - 1: I/O error (cannot create directory, cannot write file)
/// - 2: usage error (unsupported harness, collision, self-install refusal,
///        invalid mode, or missing/invalid live-mode configuration)
#[allow(clippy::too_many_arguments)]
pub fn execute_init(
    out: &mut impl Write,
    err: &mut impl Write,
    agent_name: &str,
    mode: InitMode,
    ingest_url: &str,
    workspace_id: &str,
    agent_id: &str,
    repository_id: Option<&str>,
    docker_network: &str,
) -> i32 {
    let cwd = match std::env::current_dir() {
        Ok(d) => d,
        Err(e) => {
            let _ = writeln!(err, "scryrs init: cannot determine current directory: {e}");
            return 1;
        }
    };

    let source_root = detect_scryrs_source_checkout(&cwd);

    // Determine the target base directory.
    // For Pi inside the scryrs source checkout: use the detected checkout root.
    // For all other cases (consumer projects, Claude Code, etc.): use CWD.
    let target_base: &Path = match (&source_root, agent_name) {
        (Some(root), "pi") => root,
        _ => &cwd,
    };

    // Harness-specific self-install policy:
    // - Live mode is always refused in the scryrs source checkout.
    // - In local mode, only Pi may install into the source checkout.
    if source_root.is_some() {
        if mode == InitMode::Live {
            let _ = writeln!(
                err,
                "scryrs init: live mode is not allowed in the scryrs source repository"
            );
            let _ = writeln!(
                err,
                "Live mode is the default and configures a consumer project for remote ingest."
            );
            if agent_name == "pi" {
                let _ = writeln!(
                    err,
                    "Use `scryrs init --agent pi --mode local` here for dogfooding, or run live init from a consumer project."
                );
            } else {
                let _ = writeln!(
                    err,
                    "Run live init from your target project directory instead."
                );
            }
            return 2;
        }
        if agent_name != "pi" {
            let _ = writeln!(
                err,
                "scryrs init: refusing to install into the scryrs source repository"
            );
            let _ = writeln!(
                err,
                "Consumer config must not be written into the scryrs source repo."
            );
            let _ = writeln!(
                err,
                "Run scryrs init from your target project directory instead."
            );
            return 2;
        }
    }

    // Live-mode resolution: merge CLI flags over the shared precedence chain
    // (flags > env > .scryrs/.env > scryrs.json remote) before any filesystem
    // writes. Unresolved required config fails fast with remediation guidance.
    let mut resolved_config: Option<RemoteConfig> = None;
    let mut resolved_docker_network: Option<String> = None;
    if mode == InitMode::Live {
        let overrides = RemoteOverrides {
            ingest_url: opt_nonempty(ingest_url),
            repository_id: repository_id.and_then(opt_nonempty),
            workspace_id: opt_nonempty(workspace_id),
            agent_id: opt_nonempty(agent_id),
            timeout_ms: None,
        };
        match remote_config::resolve_remote_config_with(Some(&cwd), &overrides) {
            Ok(Some(resolved)) => resolved_config = Some(resolved.config),
            Ok(None) => {
                write_missing_live_bootstrap_guidance(err, "ingest_url");
                return 2;
            }
            Err(e) => {
                write_missing_live_bootstrap_guidance(err, e.missing_field());
                return 2;
            }
        }

        match remote_config::resolve_docker_network(Some(&cwd), Some(docker_network)) {
            Some(value) => resolved_docker_network = Some(value),
            None => {
                write_missing_live_bootstrap_guidance(err, "docker_network");
                return 2;
            }
        }
    }

    // Resolve the install action, rejecting an unsupported harness *before*
    // scaffolding so an unknown name leaves the filesystem untouched.
    enum Action {
        ClaudeCode,
        File(&'static HarnessEntry),
    }
    let action = match agent_name {
        "claude-code" => Action::ClaudeCode,
        other => match find_harness(other) {
            Some(entry) => Action::File(entry),
            None => {
                let _ = writeln!(
                    err,
                    "scryrs init: '{agent_name}' is not a supported harness"
                );
                let _ = write!(err, "Supported harnesses: ");
                for (i, name) in SUPPORTED_HARNESSES.iter().enumerate() {
                    if i > 0 {
                        let _ = write!(err, ", ");
                    }
                    let _ = write!(err, "{name}");
                }
                let _ = writeln!(err);
                return 2;
            }
        },
    };

    if let Action::File(entry) = &action {
        let code = validate_file_harness_target(err, target_base, entry);
        if code != 0 {
            return code;
        }
    }

    if mode == InitMode::Live {
        let config = match resolved_config.as_ref() {
            Some(c) => c,
            None => {
                let _ = writeln!(err, "scryrs init: internal error: live config not resolved");
                return 1;
            }
        };
        let docker_network = match resolved_docker_network.as_deref() {
            Some(value) => value,
            None => {
                let _ = writeln!(
                    err,
                    "scryrs init: internal error: docker network not resolved"
                );
                return 1;
            }
        };
        let code = validate_live_bootstrap_state(err, target_base, config, docker_network);
        if code != 0 {
            return code;
        }
    }

    // Scaffold `.scryrs/` runtime directory. Local mode creates the full
    // trace store; live mode creates warning-log directories only.
    let code = scaffold_scryrs(out, err, target_base, mode);
    if code != 0 {
        return code;
    }

    // Live-mode: write or merge the project's `scryrs.json` `remote` section,
    // scaffold the managed `.scryrs/.env`, and scaffold `.scryrs/compose.yml`.
    if mode == InitMode::Live {
        let config = match resolved_config.as_ref() {
            Some(c) => c,
            None => {
                let _ = writeln!(err, "scryrs init: internal error: live config not resolved");
                return 1;
            }
        };
        let docker_network = match resolved_docker_network.as_deref() {
            Some(value) => value,
            None => {
                let _ = writeln!(
                    err,
                    "scryrs init: internal error: docker network not resolved"
                );
                return 1;
            }
        };
        let code = write_live_manifest(err, target_base, config, docker_network);
        if code != 0 {
            return code;
        }
        let code = scaffold_env_template(err, &target_base.join(".scryrs"));
        if code != 0 {
            return code;
        }
        let code = scaffold_compose_file(err, &target_base.join(".scryrs"));
        if code != 0 {
            return code;
        }
    }

    match action {
        Action::ClaudeCode => {
            let code = install_claude_code(out, err, target_base);
            if code != 0 {
                return code;
            }
        }
        Action::File(entry) => {
            let code = install_file_harness(out, err, target_base, entry);
            if code != 0 {
                return code;
            }
        }
    }

    // Print mode-specific next-step text.
    match mode {
        InitMode::Local => {
            // next-step text is already printed by install functions
        }
        InitMode::Live => {
            let config = match resolved_config.as_ref() {
                Some(c) => c,
                None => {
                    let _ = writeln!(err, "scryrs init: internal error: live config not resolved");
                    return 1;
                }
            };
            let docker_network = match resolved_docker_network.as_deref() {
                Some(value) => value,
                None => {
                    let _ = writeln!(
                        err,
                        "scryrs init: internal error: docker network not resolved"
                    );
                    return 1;
                }
            };
            if write_live_next_steps(out, config, docker_network).is_err() {
                return 1;
            }
        }
    }

    0
}

// ---------------------------------------------------------------------------
// .scryrs/ runtime store scaffolding (harness-agnostic)
// ---------------------------------------------------------------------------

/// Scaffold the `.scryrs/` runtime directory at `base`.
///
/// Local mode: creates `.scryrs/scryrs.db`, `.scryrs/.gitignore`.
/// Live mode: creates `.scryrs/`, `.scryrs/.gitignore`, `.scryrs/hooks/` only
/// (no local database).
///
/// Idempotent: existing files are preserved (the store is opened, never clobbered).
///
/// Returns 0 on success, or 1 on an I/O error.
fn scaffold_scryrs(out: &mut impl Write, err: &mut impl Write, base: &Path, mode: InitMode) -> i32 {
    let scryrs_dir = base.join(".scryrs");
    if let Err(e) = fs::create_dir_all(&scryrs_dir) {
        let _ = writeln!(
            err,
            "scryrs init: cannot create {}: {e}",
            scryrs_dir.display()
        );
        return 1;
    }

    // Write `.gitignore` only when absent, so a user's edits are never clobbered.
    let gitignore_path = scryrs_dir.join(".gitignore");
    if !gitignore_path.exists() {
        if let Err(e) = fs::write(&gitignore_path, SCRYRS_GITIGNORE) {
            let _ = writeln!(
                err,
                "scryrs init: cannot write {}: {e}",
                gitignore_path.display()
            );
            return 1;
        }
    }

    match mode {
        InitMode::Local => {
            // Initialize the trace store schema (idempotent; preserves existing data).
            if let Err(reason) = init_trace_store(&scryrs_dir.join("scryrs.db")) {
                let _ = writeln!(err, "scryrs init: cannot initialize trace store: {reason}");
                return 1;
            }
            let _ = write!(out, "{SCRYRS_SCAFFOLD_NOTE}");
        }
        InitMode::Live => {
            // Create `.scryrs/hooks/` for warning logs; no local database.
            let hooks_dir = scryrs_dir.join("hooks");
            if let Err(e) = fs::create_dir_all(&hooks_dir) {
                let _ = writeln!(
                    err,
                    "scryrs init: cannot create {}: {e}",
                    hooks_dir.display()
                );
                return 1;
            }
            let _ = write!(
                out,
                "Initialized .scryrs/ for live-mode warning logs (.scryrs/.gitignore, .scryrs/hooks/)\n\n"
            );
        }
    }
    0
}

/// Open (creating + initializing the schema) the canonical trace store.
#[cfg(feature = "core")]
fn init_trace_store(db_path: &Path) -> Result<(), String> {
    scryrs_core::EventStore::open(db_path)
        .map(|_store| ())
        .map_err(|e| e.to_string())
}

/// Without the `core` feature the schema cannot be created here; the hook
/// initializes the store lazily on the first recorded event.
#[cfg(not(feature = "core"))]
fn init_trace_store(_db_path: &Path) -> Result<(), String> {
    Ok(())
}

// ---------------------------------------------------------------------------
// Claude Code: create-or-merge .claude/settings.json
// ---------------------------------------------------------------------------

/// Create-or-merge `.claude/settings.json` with the native command hook.
/// Preserves unrelated keys; idempotent across re-runs.
fn install_claude_code(out: &mut impl Write, err: &mut impl Write, target_base: &Path) -> i32 {
    use serde_json::{Map, Value, json};

    let claude_dir = target_base.join(".claude");
    if let Err(e) = fs::create_dir_all(&claude_dir) {
        let _ = writeln!(
            err,
            "scryrs init: cannot create {}: {e}",
            claude_dir.display()
        );
        return 1;
    }

    let settings_path = claude_dir.join("settings.json");

    // Load existing settings (or start from an empty object).
    let mut root: Value = if settings_path.exists() {
        match fs::read_to_string(&settings_path) {
            Ok(contents) => match serde_json::from_str(&contents) {
                Ok(Value::Object(map)) => Value::Object(map),
                Ok(_other) => {
                    let _ = writeln!(
                        err,
                        "scryrs init: {} is not a JSON object; refusing to overwrite",
                        settings_path.display()
                    );
                    return 2;
                }
                Err(e) => {
                    let _ = writeln!(
                        err,
                        "scryrs init: cannot parse {}: {e}",
                        settings_path.display()
                    );
                    return 2;
                }
            },
            Err(e) => {
                let _ = writeln!(
                    err,
                    "scryrs init: cannot read {}: {e}",
                    settings_path.display()
                );
                return 1;
            }
        }
    } else {
        Value::Object(Map::new())
    };

    // root must be an object at this point.
    let obj = match root.as_object_mut() {
        Some(o) => o,
        None => {
            let _ = writeln!(err, "scryrs init: internal error building settings object");
            return 1;
        }
    };

    // Ensure `hooks` is an object.
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| Value::Object(Map::new()));
    let hooks = match hooks.as_object_mut() {
        Some(h) => h,
        None => {
            let _ = writeln!(
                err,
                "scryrs init: existing \"hooks\" is not an object; refusing to overwrite"
            );
            return 2;
        }
    };

    // Ensure `PreToolUse` is an array.
    let pre = hooks
        .entry("PreToolUse")
        .or_insert_with(|| Value::Array(Vec::new()));
    let pre = match pre.as_array_mut() {
        Some(a) => a,
        None => {
            let _ = writeln!(
                err,
                "scryrs init: existing \"PreToolUse\" is not an array; refusing to overwrite"
            );
            return 2;
        }
    };

    // Idempotency: bail out unchanged if our command is already registered.
    let already = pre.iter().any(|entry| {
        entry
            .get("hooks")
            .and_then(Value::as_array)
            .map(|hs| {
                hs.iter().any(|h| {
                    h.get("type").and_then(Value::as_str) == Some("command")
                        && h.get("command").and_then(Value::as_str) == Some(CLAUDE_HOOK_COMMAND)
                })
            })
            .unwrap_or(false)
    });

    if !already {
        pre.push(json!({
            "matcher": "",
            "hooks": [ { "type": "command", "command": CLAUDE_HOOK_COMMAND } ]
        }));
    }

    // Serialize with a trailing newline for stable on-disk form.
    let serialized = match serde_json::to_string_pretty(&root) {
        Ok(s) => s,
        Err(e) => {
            let _ = writeln!(err, "scryrs init: cannot serialize settings: {e}");
            return 1;
        }
    };
    if let Err(e) = fs::write(&settings_path, format!("{serialized}\n")) {
        let _ = writeln!(
            err,
            "scryrs init: cannot write {}: {e}",
            settings_path.display()
        );
        return 1;
    }

    let _ = write!(out, "{CLAUDE_NEXT_STEPS}");
    0
}

// ---------------------------------------------------------------------------
// File-based harnesses (Pi)
// ---------------------------------------------------------------------------

fn install_file_harness(
    out: &mut impl Write,
    err: &mut impl Write,
    target_base: &Path,
    entry: &HarnessEntry,
) -> i32 {
    let target_dir = target_base.join(entry.target_dir);
    if let Err(e) = fs::create_dir_all(&target_dir) {
        let _ = writeln!(
            err,
            "scryrs init: cannot create {}: {e}",
            target_dir.display()
        );
        return 1;
    }

    let target_path = target_dir.join(entry.target_filename);
    if !target_path.exists() {
        if let Err(e) = fs::write(&target_path, entry.source_asset) {
            let _ = writeln!(
                err,
                "scryrs init: cannot write {}: {e}",
                target_path.display()
            );
            return 1;
        }
    }

    let _ = write!(out, "{}", entry.next_steps);
    0
}

fn validate_file_harness_target(
    err: &mut impl Write,
    target_base: &Path,
    entry: &HarnessEntry,
) -> i32 {
    let target_path = target_base
        .join(entry.target_dir)
        .join(entry.target_filename);
    if !target_path.exists() {
        return 0;
    }

    let existing = match fs::read(&target_path) {
        Ok(contents) => contents,
        Err(error) => {
            let _ = writeln!(
                err,
                "scryrs init: cannot read {}: {error}",
                target_path.display()
            );
            return 1;
        }
    };

    if existing == entry.source_asset.as_bytes() {
        return 0;
    }

    let _ = writeln!(
        err,
        "scryrs init: {} already exists with different content",
        target_path.display()
    );
    let _ = writeln!(err, "Remove the file manually and rerun scryrs init.");
    let _ = writeln!(err, "See `scryrs --help`");
    2
}

// ---------------------------------------------------------------------------
// Self-install boundary detection
// ---------------------------------------------------------------------------

/// Walk parent directories from `cwd` looking for the scryrs source checkout.
///
/// Returns `Some(root)` when BOTH markers are found in the same ancestor directory:
/// 1. `Cargo.toml` exists and contains the string `scryrs-cli`, AND
/// 2. `hooks/claude-code/` exists as a subdirectory.
///
/// The returned path is the directory containing both markers (the checkout root).
/// Returns `None` when no matching ancestor directory is found.
///
/// The dual-marker heuristic prevents false positives: a user project would
/// need to both include scryrs-cli as a workspace member AND clone the
/// hooks/claude-code/ directory structure.
fn detect_scryrs_source_checkout(cwd: &Path) -> Option<PathBuf> {
    let mut current = Some(cwd);

    while let Some(dir) = current {
        let cargo_toml = dir.join("Cargo.toml");
        let hooks_claude_code = dir.join("hooks").join("claude-code");

        if cargo_toml.exists() && hooks_claude_code.is_dir() {
            // Both structural markers present — check content.
            if let Ok(contents) = fs::read_to_string(&cargo_toml) {
                if contents.contains("scryrs-cli") {
                    return Some(dir.to_path_buf());
                }
            }
        }

        current = dir.parent();
    }

    None
}

// ---------------------------------------------------------------------------
// Live-mode: validation and project manifest
// ---------------------------------------------------------------------------

/// Deterministic post-install instructions for live mode.
fn write_live_next_steps(
    out: &mut impl Write,
    config: &RemoteConfig,
    docker_network: &str,
) -> std::io::Result<()> {
    writeln!(
        out,
        "scryrs live-mode remote ingest configured (scryrs.json remote is the committed source of truth; .scryrs/compose.yml is the managed bootstrap; .scryrs/.env holds local overrides only)\n\nRemote server endpoint: {}\nExternal Docker network: {}\nrepository_id is derived from the Git remote origin; agent_id is autogenerated per container.\nNo local .scryrs/scryrs.db was created.\n\nNext steps:\n  1. Ensure the `scryrs-server:latest` image is available to Docker.\n  2. Start the managed workspace live server with `scryrs up`.\n  3. Restart or reload your agent harness for the hook to take effect.",
        config.ingest_url, docker_network
    )
}

/// Coerce a CLI flag value to `Some(trimmed)` when non-empty, else `None`.
fn opt_nonempty(value: &str) -> Option<String> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

/// Overrides-only `.scryrs/.env` stub written by live-mode `init`.
///
/// The committed source of truth for live config is `scryrs.json` `remote`.
/// This gitignored file exists only so an operator can override per-machine
/// values locally; `init` never pre-populates it with managed values.
const SCRYRS_ENV_STUB: &str = concat!(
    "# scryrs local overrides (gitignored)\n",
    "# The committed source of truth for live config is scryrs.json `remote`\n",
    "# (ingest_url, workspace_id, docker_network). repository_id is derived from\n",
    "# the Git remote origin and agent_id is autogenerated per container.\n",
    "#\n",
    "# Uncomment and set any of the following to override the committed defaults\n",
    "# on this machine only:\n",
    "#\n",
    "# SCRYRS_REMOTE_INGEST_URL=\n",
    "# SCRYRS_REPOSITORY_ID=\n",
    "# SCRYRS_WORKSPACE_ID=\n",
    "# SCRYRS_AGENT_ID=\n",
    "# SCRYRS_REMOTE_TIMEOUT_MS=\n",
    "# SCRYRS_DOCKER_NETWORK=\n",
);

fn write_missing_live_bootstrap_guidance(err: &mut impl Write, missing_field: &str) {
    let _ = writeln!(
        err,
        "scryrs init: live mode is the default but {missing_field} is not configured"
    );
    let _ = writeln!(
        err,
        "Set ingest_url, workspace_id, and docker_network in scryrs.json `remote` (the committed source of truth),"
    );
    let _ = writeln!(
        err,
        "or provide them via flags or .scryrs/.env overrides (e.g. {SCRYRS_DOCKER_NETWORK_ENV}),"
    );
    let _ = writeln!(
        err,
        "or rerun with --mode local for local-only, zero-network operation."
    );
    let _ = writeln!(err, "See `scryrs --help`");
}

fn validate_live_bootstrap_state(
    err: &mut impl Write,
    target_base: &Path,
    config: &RemoteConfig,
    docker_network: &str,
) -> i32 {
    let code = validate_live_manifest_state(err, target_base, config, docker_network);
    if code != 0 {
        return code;
    }

    // `.scryrs/.env` is overrides-only — `init` no longer writes managed values
    // there, so there is nothing to conflict-check. Only the managed
    // `compose.yml` template is validated for divergence.
    let scryrs_dir = target_base.join(".scryrs");
    let compose_path = scryrs_dir.join("compose.yml");
    if compose_path.exists() {
        let existing = match fs::read_to_string(&compose_path) {
            Ok(contents) => contents,
            Err(error) => {
                let _ = writeln!(
                    err,
                    "scryrs init: cannot read {}: {error}",
                    compose_path.display()
                );
                return 1;
            }
        };
        if existing != SCRYRS_COMPOSE_TEMPLATE {
            let _ = writeln!(
                err,
                "scryrs init: existing {} conflicts with managed live bootstrap",
                compose_path.display()
            );
            return 2;
        }
    }

    0
}

fn validate_live_manifest_state(
    err: &mut impl Write,
    target_base: &Path,
    config: &RemoteConfig,
    docker_network: &str,
) -> i32 {
    let manifest_path = target_base.join("scryrs.json");
    let root = match load_manifest_root(err, &manifest_path) {
        Ok(root) => root,
        Err(code) => return code,
    };

    let Some(existing_remote) = root.get("remote") else {
        return 0;
    };
    let Some(existing_remote) = existing_remote.as_object() else {
        let _ = writeln!(
            err,
            "scryrs init: existing \"remote\" in {} is not an object; refusing to overwrite",
            manifest_path.display()
        );
        return 2;
    };

    let desired_remote = desired_remote_object(config, docker_network);
    for key in ["ingest_url", "workspace_id", "docker_network"] {
        if let Some(current) = existing_remote.get(key).and_then(|value| value.as_str()) {
            if current
                != desired_remote
                    .get(key)
                    .and_then(|value| value.as_str())
                    .unwrap_or("")
            {
                let _ = writeln!(
                    err,
                    "scryrs init: existing remote.{key} in {} conflicts with managed live bootstrap",
                    manifest_path.display()
                );
                return 2;
            }
        }
    }

    0
}

/// Scaffold `.scryrs/.env` as an overrides-only stub.
///
/// Creates the commented stub only when no `.env` exists. An existing file is
/// preserved verbatim — it is the operator's local-overrides surface and is
/// never rewritten with managed values.
fn scaffold_env_template(err: &mut impl Write, scryrs_dir: &Path) -> i32 {
    let env_path = scryrs_dir.join(".env");
    if env_path.exists() {
        return 0;
    }

    if let Err(error) = fs::write(&env_path, SCRYRS_ENV_STUB) {
        let _ = writeln!(
            err,
            "scryrs init: cannot write {}: {error}",
            env_path.display()
        );
        return 1;
    }

    0
}

fn scaffold_compose_file(err: &mut impl Write, scryrs_dir: &Path) -> i32 {
    let compose_path = scryrs_dir.join("compose.yml");
    if compose_path.exists() {
        return 0;
    }

    if let Err(error) = fs::write(&compose_path, SCRYRS_COMPOSE_TEMPLATE) {
        let _ = writeln!(
            err,
            "scryrs init: cannot write {}: {error}",
            compose_path.display()
        );
        return 1;
    }

    0
}

/// Write or merge the `remote` section of the target project's `scryrs.json`.
///
/// Creates the file if missing; merges into existing manifest, preserving
/// unrelated top-level keys. Refuses to overwrite a non-object `scryrs.json`.
fn write_live_manifest(
    err: &mut impl Write,
    target_base: &Path,
    config: &RemoteConfig,
    docker_network: &str,
) -> i32 {
    use serde_json::Value;

    let manifest_path = target_base.join("scryrs.json");
    let mut root = match load_manifest_root(err, &manifest_path) {
        Ok(root) => root,
        Err(code) => return code,
    };

    let desired_remote = desired_remote_object(config, docker_network);
    if root.get("remote").and_then(Value::as_object) == Some(&desired_remote) {
        return 0;
    }

    let obj = match root.as_object_mut() {
        Some(object) => object,
        None => {
            let _ = writeln!(
                err,
                "scryrs init: internal error building scryrs.json object"
            );
            return 1;
        }
    };
    obj.insert("remote".to_string(), Value::Object(desired_remote));

    let serialized = match serde_json::to_string_pretty(&root) {
        Ok(contents) => contents,
        Err(error) => {
            let _ = writeln!(err, "scryrs init: cannot serialize scryrs.json: {error}");
            return 1;
        }
    };
    if let Err(error) = fs::write(&manifest_path, format!("{serialized}\n")) {
        let _ = writeln!(
            err,
            "scryrs init: cannot write {}: {error}",
            manifest_path.display()
        );
        return 1;
    }

    0
}

/// Build the committed `remote` object written by live-mode `init`.
///
/// Only the genuinely-shared constants are committed: `ingest_url`,
/// `workspace_id`, and `docker_network`. `repository_id` (Git-derived) and
/// `agent_id` (autogenerated per container) are intentionally absent —
/// resolution supplies them at runtime.
fn desired_remote_object(
    config: &RemoteConfig,
    docker_network: &str,
) -> serde_json::Map<String, serde_json::Value> {
    use serde_json::{Map, Value};

    let mut remote = Map::new();
    remote.insert(
        "ingest_url".to_string(),
        Value::String(config.ingest_url.clone()),
    );
    remote.insert(
        "workspace_id".to_string(),
        Value::String(config.workspace_id.clone()),
    );
    remote.insert(
        "docker_network".to_string(),
        Value::String(docker_network.to_string()),
    );
    remote
}

fn load_manifest_root(
    err: &mut impl Write,
    manifest_path: &Path,
) -> Result<serde_json::Value, i32> {
    use serde_json::{Map, Value};

    if !manifest_path.exists() {
        return Ok(Value::Object(Map::new()));
    }

    let contents = match fs::read_to_string(manifest_path) {
        Ok(contents) => contents,
        Err(error) => {
            let _ = writeln!(
                err,
                "scryrs init: cannot read {}: {error}",
                manifest_path.display()
            );
            return Err(1);
        }
    };

    match serde_json::from_str(&contents) {
        Ok(Value::Object(map)) => Ok(Value::Object(map)),
        Ok(_other) => {
            let _ = writeln!(
                err,
                "scryrs init: {} is not a JSON object; refusing to overwrite",
                manifest_path.display()
            );
            Err(2)
        }
        Err(error) => {
            let _ = writeln!(
                err,
                "scryrs init: cannot parse {}: {error}",
                manifest_path.display()
            );
            Err(2)
        }
    }
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Linear scan through the file-based registry for a harness matching `agent_name`.
fn find_harness(agent_name: &str) -> Option<&'static HarnessEntry> {
    FILE_HARNESS_REGISTRY
        .iter()
        .find(|e| e.agent_name == agent_name)
}
