//! Runtime trace-transport configuration (`scryrs setup <mode>`).
//!
//! `setup` owns all runtime-config scaffolding, kept deliberately separate from
//! `scryrs init` (which installs only the harness hook). Two modes:
//!
//! - **local**: scaffold the single-machine SQLite store under `.scryrs/`
//!   (`.scryrs/scryrs.db`, `.scryrs/.gitignore`). Manifest-agnostic — never
//!   touches `scryrs.json`.
//! - **live**: create-or-merge the `scryrs.json` `remote` section as the
//!   committed source of truth. Requires only `ingest_url` + `workspace_id`
//!   (`repository_id` derives from the Git remote origin and `agent_id` is
//!   autogenerated at runtime — neither is committed). The self-hosted compose
//!   stack (`.scryrs/compose.yml`, overrides-only `.scryrs/.env`, and the
//!   `docker_network`) is an explicit opt-in via `--with-compose`.

use std::fs;
use std::io::Write;
use std::path::Path;

use crate::init::detect_scryrs_source_checkout;
use crate::init_prompt::{
    DialoguerInitPrompt, InitPrompt, InitPromptError, PromptSpec, TerminalState,
};
use crate::live_bootstrap::{SCRYRS_COMPOSE_TEMPLATE, SCRYRS_DOCKER_NETWORK_ENV};
use crate::remote_config::{self, RemoteOverrides, ResolvedRemoteInputs};

/// Supported modes, listed in stable order for the usage error.
const SUPPORTED_MODES: &[&str] = &["live", "local"];

/// `.gitignore` written into `.scryrs/` so runtime trace data is never
/// committed. Ignores everything except the ignore file itself.
const SCRYRS_GITIGNORE: &str = concat!(
    "# scryrs runtime data — do not commit\n",
    "*\n",
    "!.gitignore\n",
);

/// Deterministic confirmation printed after the local `.scryrs/` store is scaffolded.
const SETUP_LOCAL_NOTE: &str = concat!(
    "Configured local trace transport: .scryrs/scryrs.db (.scryrs/.gitignore)\n",
    "\n",
    "Next steps:\n",
    "  1. Reload your agent harness for the hook to record into the local store.\n",
);

/// Overrides-only `.scryrs/.env` stub written by the compose opt-in.
///
/// The committed source of truth for live config is `scryrs.json` `remote`.
/// This gitignored file exists only so an operator can override per-machine
/// values locally; `setup` never pre-populates it with managed values.
const SCRYRS_ENV_STUB: &str = concat!(
    "# scryrs local overrides (gitignored)\n",
    "# The committed source of truth for live config is scryrs.json `remote`\n",
    "# (ingest_url, workspace_id, docker_network). repository_id is derived from\n",
    "# the Git remote origin and agent_id is autogenerated per container.\n",
    "#\n",
    "# Uncomment and set any of the following to override the committed defaults\n",
    "# on this machine only:\n",
    "#\n",
    "# SCRYRS_REMOTE_INGEST_URL=\n",
    "# SCRYRS_REPOSITORY_ID=\n",
    "# SCRYRS_WORKSPACE_ID=\n",
    "# SCRYRS_AGENT_ID=\n",
    "# SCRYRS_REMOTE_TIMEOUT_MS=\n",
    "# SCRYRS_DOCKER_NETWORK=\n",
);

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

/// Setup mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum SetupMode {
    /// Local SQLite trace store.
    Local,
    /// Remote ingest via scryrs server (writes project scryrs.json).
    Live,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct SetupExecutionOptions {
    pub(crate) no_interactive: bool,
    pub(crate) with_compose: bool,
    pub(crate) terminal_state: TerminalState,
}

impl SetupExecutionOptions {
    fn detect(no_interactive: bool, with_compose: bool) -> Self {
        Self {
            no_interactive,
            with_compose,
            terminal_state: TerminalState::detect(),
        }
    }
}

/// Execute the `scryrs setup <mode>` subcommand.
///
/// Returns the process exit code:
/// - 0: configuration scaffolded successfully
/// - 1: I/O error (cannot create directory, cannot write file)
/// - 2: usage error (unknown/missing mode, source-checkout refusal, or
///        missing/invalid/conflicting live configuration)
#[allow(clippy::too_many_arguments)]
pub fn execute_setup(
    out: &mut impl Write,
    err: &mut impl Write,
    mode: SetupMode,
    ingest_url: &str,
    workspace_id: &str,
    repository_id: Option<&str>,
    agent_id: &str,
    docker_network: &str,
    with_compose: bool,
    no_interactive: bool,
) -> i32 {
    let mut prompt = DialoguerInitPrompt::default();
    execute_setup_with_prompt(
        out,
        err,
        mode,
        ingest_url,
        workspace_id,
        repository_id,
        agent_id,
        docker_network,
        SetupExecutionOptions::detect(no_interactive, with_compose),
        &mut prompt,
    )
}

#[allow(clippy::too_many_arguments)]
pub(crate) fn execute_setup_with_prompt<P: InitPrompt>(
    out: &mut impl Write,
    err: &mut impl Write,
    mode: SetupMode,
    ingest_url: &str,
    workspace_id: &str,
    repository_id: Option<&str>,
    agent_id: &str,
    docker_network: &str,
    options: SetupExecutionOptions,
    prompt: &mut P,
) -> i32 {
    let cwd = match std::env::current_dir() {
        Ok(d) => d,
        Err(e) => {
            let _ = writeln!(err, "scryrs setup: cannot determine current directory: {e}");
            return 1;
        }
    };

    match mode {
        SetupMode::Local => setup_local(out, err, &cwd),
        SetupMode::Live => setup_live(
            out,
            err,
            &cwd,
            ingest_url,
            workspace_id,
            repository_id,
            agent_id,
            docker_network,
            options,
            prompt,
        ),
    }
}

/// Write the "mode is required" usage error (missing positional). Exit 2.
pub(crate) fn write_missing_mode(err: &mut impl Write) {
    let _ = writeln!(err, "scryrs setup: a mode (local or live) is required");
    let _ = writeln!(err, "Usage: scryrs setup <local|live>");
    let _ = writeln!(err, "See `scryrs --help`");
}

/// Write the "unknown mode" usage error, listing the supported modes. Exit 2.
pub(crate) fn write_unknown_mode(err: &mut impl Write, mode: &str) {
    let _ = writeln!(err, "scryrs setup: '{mode}' is not a supported mode");
    let _ = write!(err, "Supported modes: ");
    for (i, name) in SUPPORTED_MODES.iter().enumerate() {
        if i > 0 {
            let _ = write!(err, ", ");
        }
        let _ = write!(err, "{name}");
    }
    let _ = writeln!(err);
    let _ = writeln!(err, "See `scryrs --help`");
}

// ---------------------------------------------------------------------------
// setup local
// ---------------------------------------------------------------------------

/// Scaffold the local SQLite trace store. Idempotent; never touches `scryrs.json`.
/// Allowed inside the scryrs source checkout for dogfooding.
fn setup_local(out: &mut impl Write, err: &mut impl Write, cwd: &Path) -> i32 {
    let scryrs_dir = cwd.join(".scryrs");
    if let Err(e) = fs::create_dir_all(&scryrs_dir) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot create {}: {e}",
            scryrs_dir.display()
        );
        return 1;
    }

    let gitignore_path = scryrs_dir.join(".gitignore");
    if !gitignore_path.exists() {
        if let Err(e) = fs::write(&gitignore_path, SCRYRS_GITIGNORE) {
            let _ = writeln!(
                err,
                "scryrs setup: cannot write {}: {e}",
                gitignore_path.display()
            );
            return 1;
        }
    }

    // Initialize the trace store schema (idempotent; preserves existing data).
    if let Err(reason) = init_trace_store(&scryrs_dir.join("scryrs.db")) {
        let _ = writeln!(err, "scryrs setup: cannot initialize trace store: {reason}");
        return 1;
    }

    let _ = write!(out, "{SETUP_LOCAL_NOTE}");
    0
}

/// Open (creating + initializing the schema) the canonical trace store.
#[cfg(feature = "core")]
fn init_trace_store(db_path: &Path) -> Result<(), String> {
    scryrs_core::EventStore::open(db_path)
        .map(|_store| ())
        .map_err(|e| e.to_string())
}

/// Without the `core` feature the schema cannot be created here; the hook
/// initializes the store lazily on the first recorded event.
#[cfg(not(feature = "core"))]
fn init_trace_store(_db_path: &Path) -> Result<(), String> {
    Ok(())
}

// ---------------------------------------------------------------------------
// setup live
// ---------------------------------------------------------------------------

#[allow(clippy::too_many_arguments)]
fn setup_live<P: InitPrompt>(
    out: &mut impl Write,
    err: &mut impl Write,
    cwd: &Path,
    ingest_url: &str,
    workspace_id: &str,
    repository_id: Option<&str>,
    agent_id: &str,
    docker_network: &str,
    options: SetupExecutionOptions,
    prompt: &mut P,
) -> i32 {
    // Live setup configures consumer-project remote state; refuse it inside the
    // scryrs source checkout (`setup local` remains allowed there for dogfooding).
    if detect_scryrs_source_checkout(cwd).is_some() {
        let _ = writeln!(
            err,
            "scryrs setup: live setup is not allowed in the scryrs source repository"
        );
        let _ = writeln!(
            err,
            "Live setup must target a consumer project, not the scryrs source repository."
        );
        let _ = writeln!(
            err,
            "Run `scryrs setup live` from your target project directory instead."
        );
        return 2;
    }

    let with_compose = options.with_compose;

    // Resolve required live inputs across the shared precedence chain
    // (flags > env > .scryrs/.env > scryrs.json remote) before any writes.
    let mut resolved_inputs = remote_config::resolve_remote_inputs(
        Some(cwd),
        &RemoteOverrides {
            ingest_url: opt_nonempty(ingest_url),
            repository_id: repository_id.and_then(opt_nonempty),
            workspace_id: opt_nonempty(workspace_id),
            agent_id: opt_nonempty(agent_id),
            timeout_ms: None,
        },
    );
    let mut docker_network_value =
        remote_config::resolve_docker_network(Some(cwd), Some(docker_network));

    if let Some(missing_field) = first_missing_live_field(
        &resolved_inputs,
        docker_network_value.as_deref(),
        with_compose,
    ) {
        if options.no_interactive || !options.terminal_state.allows_prompting() {
            write_missing_live_guidance(err, missing_field, with_compose);
            return 2;
        }
        match run_live_setup_wizard(
            out,
            &mut resolved_inputs,
            &mut docker_network_value,
            with_compose,
            prompt,
        ) {
            Ok(WizardOutcome::Confirmed) => {}
            Ok(WizardOutcome::Cancelled) => return 2,
            Err(WizardError::Io(error)) => {
                let _ = writeln!(err, "scryrs setup: wizard I/O failed: {error}");
                return 1;
            }
            Err(WizardError::Prompt(InitPromptError::Cancelled)) => return 2,
            Err(WizardError::Prompt(InitPromptError::Io(error))) => {
                let _ = writeln!(err, "scryrs setup: wizard failed: {error}");
                return 1;
            }
        }
    }

    // After resolution (and any wizard collection), the required fields must be
    // present. These unwraps cannot fail given the missing-field guard above.
    let ingest_url = match resolved_inputs.ingest_url.as_deref() {
        Some(value) => value,
        None => {
            write_missing_live_guidance(err, "ingest_url", with_compose);
            return 2;
        }
    };
    let workspace_id = match resolved_inputs.workspace_id.as_deref() {
        Some(value) => value,
        None => {
            write_missing_live_guidance(err, "workspace_id", with_compose);
            return 2;
        }
    };
    let docker_network = if with_compose {
        match docker_network_value.as_deref() {
            Some(value) => Some(value),
            None => {
                write_missing_live_guidance(err, "docker_network", with_compose);
                return 2;
            }
        }
    } else {
        None
    };

    // Validate against any existing committed manifest before writing anything,
    // so a conflict leaves the filesystem untouched (no partial writes).
    let code = validate_live_state(err, cwd, ingest_url, workspace_id, docker_network);
    if code != 0 {
        return code;
    }

    // Scaffold the `.scryrs/` runtime directory (gitignore + warning-log dir).
    let code = scaffold_scryrs_live(err, cwd);
    if code != 0 {
        return code;
    }

    // Write or merge the committed `remote` section.
    let code = write_live_manifest(err, cwd, ingest_url, workspace_id, docker_network);
    if code != 0 {
        return code;
    }

    // Compose opt-in: scaffold the managed self-host stack + overrides-only .env.
    if with_compose {
        let scryrs_dir = cwd.join(".scryrs");
        let code = scaffold_env_template(err, &scryrs_dir);
        if code != 0 {
            return code;
        }
        let code = scaffold_compose_file(err, &scryrs_dir);
        if code != 0 {
            return code;
        }
    }

    if write_live_next_steps(out, ingest_url, docker_network).is_err() {
        return 1;
    }

    0
}

/// Scaffold `.scryrs/` for live mode: `.gitignore` plus the `hooks/` warning-log
/// directory. No local database is created in live mode.
fn scaffold_scryrs_live(err: &mut impl Write, base: &Path) -> i32 {
    let scryrs_dir = base.join(".scryrs");
    if let Err(e) = fs::create_dir_all(&scryrs_dir) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot create {}: {e}",
            scryrs_dir.display()
        );
        return 1;
    }

    let gitignore_path = scryrs_dir.join(".gitignore");
    if !gitignore_path.exists() {
        if let Err(e) = fs::write(&gitignore_path, SCRYRS_GITIGNORE) {
            let _ = writeln!(
                err,
                "scryrs setup: cannot write {}: {e}",
                gitignore_path.display()
            );
            return 1;
        }
    }

    let hooks_dir = scryrs_dir.join("hooks");
    if let Err(e) = fs::create_dir_all(&hooks_dir) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot create {}: {e}",
            hooks_dir.display()
        );
        return 1;
    }

    0
}

// ---------------------------------------------------------------------------
// Live config validation, manifest, and scaffolding
// ---------------------------------------------------------------------------

fn first_missing_live_field(
    resolved_inputs: &ResolvedRemoteInputs,
    docker_network: Option<&str>,
    with_compose: bool,
) -> Option<&'static str> {
    if resolved_inputs.ingest_url.is_none() {
        return Some("ingest_url");
    }
    if resolved_inputs.workspace_id.is_none() {
        return Some("workspace_id");
    }
    if with_compose && docker_network.is_none() {
        return Some("docker_network");
    }
    None
}

fn write_missing_live_guidance(err: &mut impl Write, missing_field: &str, with_compose: bool) {
    if missing_field == "docker_network" {
        let _ = writeln!(
            err,
            "scryrs setup live --with-compose: docker_network is required but not configured"
        );
        let _ = writeln!(
            err,
            "Compose scaffolding for a self-hosted live server requires a Docker network."
        );
        let _ = writeln!(
            err,
            "Provide it with --docker-network <NAME>, {SCRYRS_DOCKER_NETWORK_ENV} in the environment / .scryrs/.env, or scryrs.json remote.docker_network."
        );
        let _ = writeln!(err, "See `scryrs --help`");
        return;
    }

    let _ = writeln!(
        err,
        "scryrs setup live: {missing_field} is required but not configured"
    );
    let _ = writeln!(
        err,
        "Provide it with --{} <VALUE>, the matching SCRYRS_* environment variable / .scryrs/.env entry, or scryrs.json remote.{missing_field}.",
        missing_field.replace('_', "-")
    );
    if with_compose {
        let _ = writeln!(
            err,
            "(setup live --with-compose also requires a docker_network.)"
        );
    }
    let _ = writeln!(err, "See `scryrs --help`");
}

/// Validate the resolved live inputs against any existing committed manifest.
/// Returns 0 when safe to write, or a non-zero exit code on conflict / I/O error.
fn validate_live_state(
    err: &mut impl Write,
    cwd: &Path,
    ingest_url: &str,
    workspace_id: &str,
    docker_network: Option<&str>,
) -> i32 {
    let manifest_path = cwd.join("scryrs.json");
    let root = match load_manifest_root(err, &manifest_path) {
        Ok(root) => root,
        Err(code) => return code,
    };

    let Some(existing_remote) = root.get("remote") else {
        return 0;
    };
    let Some(existing_remote) = existing_remote.as_object() else {
        let _ = writeln!(
            err,
            "scryrs setup: existing \"remote\" in {} is not an object; refusing to overwrite",
            manifest_path.display()
        );
        return 2;
    };

    let desired = desired_remote_object(ingest_url, workspace_id, docker_network);
    for key in ["ingest_url", "workspace_id", "docker_network"] {
        let Some(current) = existing_remote.get(key).and_then(|v| v.as_str()) else {
            continue;
        };
        let desired_value = desired.get(key).and_then(|v| v.as_str());
        match desired_value {
            // Field we are writing: a divergent committed value is a conflict.
            Some(desired_value) if current != desired_value => {
                let _ = writeln!(
                    err,
                    "scryrs setup: existing remote.{key} in {} conflicts with the resolved value",
                    manifest_path.display()
                );
                let _ = writeln!(err, "See `scryrs --help`");
                return 2;
            }
            _ => {}
        }
    }

    0
}

/// Write or merge the `remote` section of the target project's `scryrs.json`.
/// Creates the file if missing; merges into an existing manifest, preserving
/// unrelated top-level keys.
fn write_live_manifest(
    err: &mut impl Write,
    cwd: &Path,
    ingest_url: &str,
    workspace_id: &str,
    docker_network: Option<&str>,
) -> i32 {
    use serde_json::Value;

    let manifest_path = cwd.join("scryrs.json");
    let mut root = match load_manifest_root(err, &manifest_path) {
        Ok(root) => root,
        Err(code) => return code,
    };

    // Merge our managed keys into any existing remote object, preserving
    // unrelated remote keys an operator may have added.
    let mut remote = root
        .get("remote")
        .and_then(Value::as_object)
        .cloned()
        .unwrap_or_default();
    for (key, value) in desired_remote_object(ingest_url, workspace_id, docker_network) {
        remote.insert(key, value);
    }

    if root.get("remote").and_then(Value::as_object) == Some(&remote) {
        return 0;
    }

    let obj = match root.as_object_mut() {
        Some(object) => object,
        None => {
            let _ = writeln!(
                err,
                "scryrs setup: internal error building scryrs.json object"
            );
            return 1;
        }
    };
    obj.insert("remote".to_string(), Value::Object(remote));

    let serialized = match serde_json::to_string_pretty(&root) {
        Ok(contents) => contents,
        Err(error) => {
            let _ = writeln!(err, "scryrs setup: cannot serialize scryrs.json: {error}");
            return 1;
        }
    };
    if let Err(error) = fs::write(&manifest_path, format!("{serialized}\n")) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot write {}: {error}",
            manifest_path.display()
        );
        return 1;
    }

    0
}

/// Build the committed `remote` object. Only genuinely-shared constants are
/// committed: `ingest_url`, `workspace_id`, and (compose opt-in only)
/// `docker_network`. `repository_id` (Git-derived) and `agent_id`
/// (autogenerated per container) are intentionally absent.
fn desired_remote_object(
    ingest_url: &str,
    workspace_id: &str,
    docker_network: Option<&str>,
) -> serde_json::Map<String, serde_json::Value> {
    use serde_json::{Map, Value};

    let mut remote = Map::new();
    remote.insert(
        "ingest_url".to_string(),
        Value::String(ingest_url.to_string()),
    );
    remote.insert(
        "workspace_id".to_string(),
        Value::String(workspace_id.to_string()),
    );
    if let Some(network) = docker_network {
        remote.insert(
            "docker_network".to_string(),
            Value::String(network.to_string()),
        );
    }
    remote
}

fn load_manifest_root(
    err: &mut impl Write,
    manifest_path: &Path,
) -> Result<serde_json::Value, i32> {
    use serde_json::{Map, Value};

    if !manifest_path.exists() {
        return Ok(Value::Object(Map::new()));
    }

    let contents = match fs::read_to_string(manifest_path) {
        Ok(contents) => contents,
        Err(error) => {
            let _ = writeln!(
                err,
                "scryrs setup: cannot read {}: {error}",
                manifest_path.display()
            );
            return Err(1);
        }
    };

    match serde_json::from_str(&contents) {
        Ok(Value::Object(map)) => Ok(Value::Object(map)),
        Ok(_other) => {
            let _ = writeln!(
                err,
                "scryrs setup: {} is not a JSON object; refusing to overwrite",
                manifest_path.display()
            );
            Err(2)
        }
        Err(error) => {
            let _ = writeln!(
                err,
                "scryrs setup: cannot parse {}: {error}",
                manifest_path.display()
            );
            Err(2)
        }
    }
}

/// Scaffold `.scryrs/.env` as an overrides-only stub (compose opt-in only).
/// An existing file is preserved verbatim — it is the operator's overrides
/// surface and is never rewritten with managed values.
fn scaffold_env_template(err: &mut impl Write, scryrs_dir: &Path) -> i32 {
    let env_path = scryrs_dir.join(".env");
    if env_path.exists() {
        return 0;
    }

    if let Err(error) = fs::write(&env_path, SCRYRS_ENV_STUB) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot write {}: {error}",
            env_path.display()
        );
        return 1;
    }

    0
}

fn scaffold_compose_file(err: &mut impl Write, scryrs_dir: &Path) -> i32 {
    let compose_path = scryrs_dir.join("compose.yml");
    if compose_path.exists() {
        let existing = match fs::read_to_string(&compose_path) {
            Ok(contents) => contents,
            Err(error) => {
                let _ = writeln!(
                    err,
                    "scryrs setup: cannot read {}: {error}",
                    compose_path.display()
                );
                return 1;
            }
        };
        if existing != SCRYRS_COMPOSE_TEMPLATE {
            let _ = writeln!(
                err,
                "scryrs setup: existing {} conflicts with the managed compose template",
                compose_path.display()
            );
            return 2;
        }
        return 0;
    }

    if let Err(error) = fs::write(&compose_path, SCRYRS_COMPOSE_TEMPLATE) {
        let _ = writeln!(
            err,
            "scryrs setup: cannot write {}: {error}",
            compose_path.display()
        );
        return 1;
    }

    0
}

/// Deterministic post-setup instructions for live mode.
fn write_live_next_steps(
    out: &mut impl Write,
    ingest_url: &str,
    docker_network: Option<&str>,
) -> std::io::Result<()> {
    writeln!(
        out,
        "scryrs live transport configured (scryrs.json remote is the committed source of truth: ingest_url, workspace_id)."
    )?;
    writeln!(out, "Remote server endpoint: {ingest_url}")?;
    writeln!(
        out,
        "repository_id is derived from the Git remote origin; agent_id is autogenerated per container."
    )?;
    match docker_network {
        Some(network) => {
            writeln!(out, "External Docker network: {network}")?;
            writeln!(
                out,
                "Managed self-host stack scaffolded: .scryrs/compose.yml (.scryrs/.env holds local overrides only)."
            )?;
            writeln!(out)?;
            writeln!(out, "Next steps:")?;
            writeln!(
                out,
                "  1. Ensure the `scryrs-server` image is available to Docker."
            )?;
            writeln!(out, "  2. Start the managed live server with `scryrs up`.")?;
            writeln!(
                out,
                "  3. Reload your agent harness for the hook to take effect."
            )?;
        }
        None => {
            writeln!(out)?;
            writeln!(out, "Next steps:")?;
            writeln!(
                out,
                "  1. Reload your agent harness for the hook to take effect."
            )?;
            writeln!(
                out,
                "  2. To self-host the live server, rerun with `scryrs setup live --with-compose`, then `scryrs up`."
            )?;
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Interactive wizard (migrated from `init`; lives on `setup live`)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WizardOutcome {
    Confirmed,
    Cancelled,
}

#[derive(Debug)]
enum WizardError {
    Io(std::io::Error),
    Prompt(InitPromptError),
}

impl From<std::io::Error> for WizardError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

impl From<InitPromptError> for WizardError {
    fn from(error: InitPromptError) -> Self {
        Self::Prompt(error)
    }
}

const INGEST_URL_PROMPT: PromptSpec = PromptSpec {
    field_name: "ingest_url",
    prompt: "Remote ingest URL",
};
const WORKSPACE_ID_PROMPT: PromptSpec = PromptSpec {
    field_name: "workspace_id",
    prompt: "Workspace ID",
};
const DOCKER_NETWORK_PROMPT: PromptSpec = PromptSpec {
    field_name: "docker_network",
    prompt: "Docker network name",
};

fn run_live_setup_wizard<P: InitPrompt>(
    out: &mut impl Write,
    resolved_inputs: &mut ResolvedRemoteInputs,
    docker_network: &mut Option<String>,
    with_compose: bool,
    prompt: &mut P,
) -> Result<WizardOutcome, WizardError> {
    writeln!(out, "scryrs setup live wizard")?;
    writeln!(
        out,
        "Missing required live config. Prompting only for unresolved committed fields."
    )?;
    writeln!(
        out,
        "Committed shared values will be written to scryrs.json `remote`; .scryrs/.env stays gitignored local overrides only."
    )?;
    writeln!(out)?;

    prompt_for_required_field(
        out,
        resolved_inputs,
        docker_network,
        prompt,
        INGEST_URL_PROMPT,
    )?;
    prompt_for_required_field(
        out,
        resolved_inputs,
        docker_network,
        prompt,
        WORKSPACE_ID_PROMPT,
    )?;
    if with_compose {
        prompt_for_required_field(
            out,
            resolved_inputs,
            docker_network,
            prompt,
            DOCKER_NETWORK_PROMPT,
        )?;
    }

    write_live_wizard_summary(
        out,
        resolved_inputs,
        docker_network.as_deref(),
        with_compose,
    )?;
    if !prompt.confirm("Write committed live config and continue?", true)? {
        writeln!(out, "Live setup cancelled. No files written.")?;
        return Ok(WizardOutcome::Cancelled);
    }

    Ok(WizardOutcome::Confirmed)
}

fn prompt_for_required_field<P: InitPrompt>(
    out: &mut impl Write,
    resolved_inputs: &mut ResolvedRemoteInputs,
    docker_network: &mut Option<String>,
    prompt: &mut P,
    spec: PromptSpec,
) -> Result<(), WizardError> {
    if spec.field_name == "ingest_url" && resolved_inputs.ingest_url.is_some() {
        return Ok(());
    }
    if spec.field_name == "workspace_id" && resolved_inputs.workspace_id.is_some() {
        return Ok(());
    }
    if spec.field_name == "docker_network" && docker_network.is_some() {
        return Ok(());
    }

    loop {
        writeln!(out, "{} ({})", spec.prompt, spec.field_name)?;
        let answer = prompt.prompt_text(&spec)?;
        let value = match validate_prompt_value(spec.field_name, &answer) {
            Ok(value) => value,
            Err(message) => {
                writeln!(out, "{message}")?;
                continue;
            }
        };
        set_prompt_value(resolved_inputs, docker_network, spec.field_name, value);
        return Ok(());
    }
}

fn validate_prompt_value(field_name: &str, value: &str) -> Result<String, &'static str> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return Err("Value cannot be empty.");
    }
    if field_name == "ingest_url" && !looks_like_ingest_url(trimmed) {
        return Err("ingest_url must start with http:// or https:// and include a host.");
    }
    Ok(trimmed.to_string())
}

fn looks_like_ingest_url(value: &str) -> bool {
    ["http://", "https://"]
        .into_iter()
        .find_map(|prefix| value.strip_prefix(prefix))
        .map(|rest| !rest.is_empty() && !rest.starts_with('/'))
        .unwrap_or(false)
}

fn set_prompt_value(
    resolved_inputs: &mut ResolvedRemoteInputs,
    docker_network: &mut Option<String>,
    field_name: &str,
    value: String,
) {
    match field_name {
        "ingest_url" => resolved_inputs.ingest_url = Some(value),
        "workspace_id" => resolved_inputs.workspace_id = Some(value),
        "docker_network" => *docker_network = Some(value),
        _ => {}
    }
}

fn write_live_wizard_summary(
    out: &mut impl Write,
    resolved_inputs: &ResolvedRemoteInputs,
    docker_network: Option<&str>,
    with_compose: bool,
) -> std::io::Result<()> {
    writeln!(out)?;
    writeln!(out, "Review committed live config:")?;
    writeln!(
        out,
        "  scryrs.json remote.ingest_url = {}",
        resolved_inputs.ingest_url.as_deref().unwrap_or("<missing>")
    )?;
    writeln!(
        out,
        "  scryrs.json remote.workspace_id = {}",
        resolved_inputs
            .workspace_id
            .as_deref()
            .unwrap_or("<missing>")
    )?;
    if with_compose {
        writeln!(
            out,
            "  scryrs.json remote.docker_network = {}",
            docker_network.unwrap_or("<missing>")
        )?;
        writeln!(out, "  .scryrs/.env = local overrides only (gitignored)")?;
    }
    writeln!(out)?;
    Ok(())
}

/// Coerce a CLI flag value to `Some(trimmed)` when non-empty, else `None`.
fn opt_nonempty(value: &str) -> Option<String> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}
